services:
  postgres:
    image: postgres:17rc1-alpine
    environment:
      POSTGRES_DB: ${APP_CONFIG__DATABASE__db_name}
      POSTGRES_USER: ${APP_CONFIG__DATABASE__user}
      POSTGRES_PASSWORD: ${APP_CONFIG__DATABASE__password}
    container_name: postgresql-container
    ports:
      - "${APP_CONFIG__DATABASE__port}:5432"
    volumes:
      - postgresql_data_spycats:/var/lib/postgresql/data
    env_file:
      - ../.env

volumes:
  postgresql_data_spycats: