"""'dts'

Revision ID: 3965f0c47eaa
Revises: 
Create Date: 2024-11-14 10:34:53.399458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3965f0c47eaa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spycatses',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spycatses'))
    )
    op.create_index(op.f('ix_spycatses_id'), 'spycatses', ['id'], unique=False)
    op.create_index(op.f('ix_spycatses_name'), 'spycatses', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spycatses_name'), table_name='spycatses')
    op.drop_index(op.f('ix_spycatses_id'), table_name='spycatses')
    op.drop_table('spycatses')
    # ### end Alembic commands ###
